export const GET_JOB_LIST = "GET_JOB_LIST"
export const GET_JOB_LIST_SUCCESS = "GET_JOB_LIST_SUCCESS"
export const GET_JOB_LIST_FAILED = "GET_JOB_LIST_FAILED"
export const GET_JOB_LIST_PAGINATION = "GET_JOB_LIST_PAGINATION"
export const GET_JOB_LIST_PAGINATION_SUCCESS = "GET_JOB_LIST_PAGINATION_SUCCESS"

export const GET_JOB_DETAIL = "GET_JOB_DETAIL"
export const GET_JOB_DETAIL_SUCCESS = "GET_JOB_DETAIL_SUCCESS"
export const GET_JOB_DETAIL_FAILED = "GET_JOB_DETAIL_FAILED"
export const CANT_GET_ANY_DATA = "CANT_GET_ANY_DATA"

